### ISSUE TITLE
Botstackjs github url change

### ISSUE THREAD

**Issue by cama** [fosterlabs/botstackjs#30]
Botstackjs new url is https://github.com/fosterlabs/botstackjs

Please update all references for NPM etc to support the change.

**Comment by webus** [comment]
@cama Just sending request from Travis-CI to FosterLab org in github. Check you email pls.

**Comment by webus** [comment]
ylopo updated

**Comment by webus** [comment]
Done. Travis CI build badge updated on Github README page

**Comment by cama** [comment]
thanks
